---
abstract: 'simple policy for enforcing use of Params::Validate'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  File::Spec: 0
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-logicLAB-RequireParamsValidate
provides:
  Perl::Critic::Policy::logicLAB::RequireParamsValidate:
    file: lib/Perl/Critic/Policy/logicLAB/RequireParamsValidate.pm
    version: 0.01
requires:
  List::MoreUtils: 0
  Params::Validate: 0
  Perl::Critic::Policy: 0
  Perl::Critic::Utils: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCPLRPV#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCPLRPV
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCPLRPV/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-Policy-logicLAB-RequireParamsValidate
  homepage: http://logiclab.jira.com/wiki/display/PCPLRPV/Home
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/jonasbn/pcplrpv
version: 0.01
